### ISSUE TITLE
build on amd64 instead arm64

### ISSUE THREAD

**Issue by dginhoux** [awaescher/MaxPower#4]
Hi, 
 
I'm trying to use your work for an older SM3000S but i'm running x86 platform.
Can you help about an unknow world for me : microsoft dotnet...
When buildind, i've errors about arm64, its normal because not the same platform.
So in dockerfile i juste change this :

`RUN dotnet publish -c Release -r linux-amd64 -o out -p:PublishSingleFile=true --self-contained true /p:AssemblyVersion=$ASSEMBLYSEMVERSION /p:Version=$SEMVERSION
`

But get an error...  dotnet publish... do i need auth token ? or other

Have a good day.

**Comment by awaescher** [comment]
It would be good to see the error details, otherwise I can just guess.
If you have the [dotnet SDK](https://dotnet.microsoft.com/en-us/download) installed on your dev machine, you can just jump into the repository's main directory and call:

```C#
dotnet run --project MaxPower
```

"MaxPower" is the name of the folder that contains the source code to run. This might be handy to test.

If you want to build your own docker file, I think you should use `linux-x64` instead of `linux-amd64`.

**Comment by dginhoux** [comment]
Hi, 

Thnak for your help, i've forget to copy the error output. I'm not windows/ms user, i hate it.
```
 => [build  9/12] WORKDIR /app/MaxPower/                                                                                                                                             0.2s 
 => ERROR [build 10/12] RUN dotnet publish -c Release -r linux-arm64 -o out -p:PublishSingleFile=true --self-contained true /p:AssemblyVersion=$ASSEMBLYSEMVERSION /p:Version=$SEMV  9.3s
------
 > [build 10/12] RUN dotnet publish -c Release -r linux-arm64 -o out -p:PublishSingleFile=true --self-contained true /p:AssemblyVersion=$ASSEMBLYSEMVERSION /p:Version=$SEMVERSION:
0.658 MSBuild version 17.8.3+195e7f5a3 for .NET
1.760   Determining projects to restore...
8.042   Restored /app/MaxTalkSharp/MaxTalkSharp.csproj (in 5.19 sec).
8.054   Restored /app/MaxPower/MaxPower.csproj (in 5.31 sec).
8.847 /usr/share/dotnet/sdk/8.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(226,5): error MSB4044: The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion". [/app/MaxTalkSharp/MaxTalkSharp.csproj]
------
Dockerfile:20
--------------------
  18 |     COPY ./MaxTalkSharp /app/MaxTalkSharp/
  19 |     WORKDIR /app/MaxPower/
  20 | >>> RUN dotnet publish -c Release -r linux-arm64 -o out -p:PublishSingleFile=true --self-contained true /p:AssemblyVersion=$ASSEMBLYSEMVERSION /p:Version=$SEMVERSION
  21 |     
  22 |     # RUNTIME CONTAINER
--------------------
ERROR: failed to solve: process "/bin/sh -c dotnet publish -c Release -r linux-arm64 -o out -p:PublishSingleFile=true --self-contained true /p:AssemblyVersion=$ASSEMBLYSEMVERSION /p:Version=$SEMVERSION" did not complete successfully: exit code: 1
```

I'll try with linux-x64 in fews minutes.

**Comment by dginhoux** [comment]
The more difficult to understand is the not found error on this webpage : https://mcr.microsoft.com/dotnet/aspnet

**Comment by awaescher** [comment]
I am not sure where this link comes from, I guess it's should be this:

https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps

Anyways. It seems that you also try to run the Dockerfile directly. If s, the version arguments are not set. Make sure to set these or change the Dockerfile to the desired version and tags.

The Dockerfile is designed to be called from the GitHub actions workflow, you can see the corresponding usage there.

**Comment by dginhoux** [comment]
Yes, i want to build it from a computer, not from github actions.

**Comment by dginhoux** [comment]
Hi,
after few times, I don't find a way to build it locally on a computer and for x86_64 platform...
Microsoft tools are so complicated to use. I don't find any working solution.

**Comment by awaescher** [comment]
I don't agree here. If you have the dotnet sdk installed you can run it with dotnet run as I wrote above. Did this work?
To build it for linux x64 you just have to use the runtime identifier I gave you above and run dotnet publish with a version string instead of the variables that are given by the GitHub actions or without the version arguments.
